import main_program as mprog

mprog.folder_file_name()
x = ['back straight', 'BALANCER', 'BALANCER1', 'BALANCER10', 'BALANCER2', 'BALANCER3', 'BALANCER4', 'BALANCER4',
     'BALANCER5', 'BALANCER6', 'BALANCER7', 'BALANCER8', 'BALANCER9', 'BALL CUP',
     'BEARING_HOUSING1', 'BEARING_HOUSING2', 'BEARING_HOUSING3', 'BEARING_HOUSING4', 'BEARING_HOUSING5', 'BOLSTER1',
     'BOLSTER2', 'BOLSTER3', 'BOLSTER4', 'BOLSTER5', 'BUSH', 'CLUCTH_ASSEMBLY1', 'CLUCTH_ASSEMBLY10',
     'CLUCTH_ASSEMBLY11', 'CLUCTH_ASSEMBLY12', 'CLUCTH_ASSEMBLY13', 'CLUCTH_ASSEMBLY14', 'CLUCTH_ASSEMBLY15',
     'CLUCTH_ASSEMBLY16', 'CLUCTH_ASSEMBLY17', 'CLUCTH_ASSEMBLY18', 'CLUCTH_ASSEMBLY19', 'CLUCTH_ASSEMBLY2',
     'CLUCTH_ASSEMBLY20', 'CLUCTH_ASSEMBLY21', 'CLUCTH_ASSEMBLY22', 'CLUCTH_ASSEMBLY23', 'CLUCTH_ASSEMBLY24',
     'CLUCTH_ASSEMBLY25', 'CLUCTH_ASSEMBLY26', 'CLUCTH_ASSEMBLY27', 'CLUCTH_ASSEMBLY28', 'CLUCTH_ASSEMBLY29',
     'CLUCTH_ASSEMBLY3', 'CLUCTH_ASSEMBLY30', 'CLUCTH_ASSEMBLY31', 'CLUCTH_ASSEMBLY32', 'CLUCTH_ASSEMBLY33',
     'CLUCTH_ASSEMBLY34', 'CLUCTH_ASSEMBLY35', 'CLUCTH_ASSEMBLY36', 'CLUCTH_ASSEMBLY4', 'CLUCTH_ASSEMBLY5',
     'CLUCTH_ASSEMBLY6', 'CLUCTH_ASSEMBLY7', 'CLUCTH_ASSEMBLY8', 'CLUCTH_ASSEMBLY9', 'COUNTER_PARTS',
     'COVER (BALL SCREW)', 'CRANK_SHAFT', 'Fixture', 'FLYWHEEL BRAKE', 'FRAME1', 'FRAME10', 'FRAME11',
     'FRAME12', 'FRAME13', 'FRAME14', 'FRAME15', 'FRAME16', 'FRAME17', 'FRAME18', 'FRAME19', 'FRAME2', 'FRAME20',
     'FRAME21', 'FRAME22', 'FRAME23', 'FRAME24', 'FRAME25', 'FRAME26', 'FRAME27', 'FRAME28', 'FRAME29', 'FRAME3',
     'FRAME30', 'FRAME31', 'FRAME32', 'FRAME33', 'FRAME34', 'FRAME35', 'FRAME36', 'FRAME37', 'FRAME38', 'FRAME39',
     'FRAME4', 'FRAME40', 'FRAME41', 'FRAME43', 'FRAME5', 'FRAME6', 'FRAME7', 'FRAME8', 'FRAME9', 'GIB1', 'GIB2',
     'HOLD MOUNTING MANIFOLD', 'inside the punch 9', 'JOINT1', 'JOINT10', 'JOINT2', 'JOINT3', 'JOINT4', 'JOINT5',
     'JOINT6', 'JOINT7', 'JOINT8', 'JOINT9', 'MAIN_GEAR1', 'MAIN_GEAR2', 'MAIN_GEAR3', 'MAIN_GEAR4',
     'OVERLOAD PROTECTER', 'Pin', 'POINT', 'POINT2', 'POINT3', 'PRESSURE_PLATE', 'SLIDE', 'SPROCKET',
     'washer left', 'washer right', 'WORM GEAR COVER', 'WORM GEAR', 'WORM WHEEL COVER', 'WORM WHEEL']
y = ['BALANCER_LEFT', 'BALANCER_RIGHT', 'CLUCTH_ASSEMBLY', 'CRANK_SHAFT', 'SLIDE_UNIT']