import win32com.client as win32
import main_program as mprog

def change_parameter2(name, i):
    if name== 'FRAME4':
        if i== 0:
            mprog.param_change('FRAME4', 'A', 150)
            mprog.param_change('FRAME4', 'B', 488)
            mprog.param_change('FRAME4', 'C', 10)
            mprog.param_change('FRAME4', 'C(a)', 45)
            mprog.param_change('FRAME4', 'D', 19)
            mprog.activatefeatrue('SN1_2580_Body', 0)
        elif i== 1:
            mprog.param_change('FRAME4', 'A', 150)
            mprog.param_change('FRAME4', 'B', 584)
            mprog.param_change('FRAME4', 'C', 12)
            mprog.param_change('FRAME4', 'C(a)', 40)
            mprog.param_change('FRAME4', 'D', 22)
            mprog.activatefeatrue('SN1_2580_Body', 0)
        elif i== 2:
            mprog.param_change('FRAME4', 'A', 170)
            mprog.param_change('FRAME4', 'B', 626)
            mprog.param_change('FRAME4', 'C', 10)
            mprog.param_change('FRAME4', 'C(a)', 45)
            mprog.param_change('FRAME4', 'D', 19)
            mprog.activatefeatrue('SN1_2580_Body', 0)
        elif i== 3:
            mprog.param_change('FRAME4', 'A', 170)
            mprog.param_change('FRAME4', 'B', 664)
            mprog.param_change('FRAME4', 'C', 13)
            mprog.param_change('FRAME4', 'C(a)', 40)
            mprog.param_change('FRAME4', 'D', 25)
            mprog.activatefeatrue('SN1_2580_Body', 0)
        elif i== 4:
            mprog.param_change('FRAME4', 'A', 90)
            mprog.param_change('FRAME4', 'B', 742)
            mprog.param_change('FRAME4', 'D', 200)
            mprog.param_change('FRAME4', 'E', 8)
            mprog.param_change('FRAME4', 'F', 13.5)
            mprog.param_change('FRAME4', 'G', 82)
            mprog.param_change('FRAME4', 'H', 14)
            mprog.param_change('FRAME4', 'I', 7)
            mprog.param_change('FRAME4', 'J(a)', 95)
            mprog.activatefeatrue('channel steel', 0)
        elif i== 5:
            mprog.param_change('FRAME4', 'A', 90)
            mprog.param_change('FRAME4', 'B', 850)
            mprog.param_change('FRAME4', 'D', 250)
            mprog.param_change('FRAME4', 'E', 9)
            mprog.param_change('FRAME4', 'F', 13)
            mprog.param_change('FRAME4', 'G', 81)
            mprog.param_change('FRAME4', 'H', 14)
            mprog.param_change('FRAME4', 'I', 7)
            mprog.param_change('FRAME4', 'J(a)', 95)
            mprog.activatefeatrue('channel steel', 0)
        elif i== 6:
            mprog.param_change('FRAME4', 'A', 90)
            mprog.param_change('FRAME4', 'B', 940)
            mprog.param_change('FRAME4', 'D', 300)
            mprog.param_change('FRAME4', 'E', 9)
            mprog.param_change('FRAME4', 'F', 13)
            mprog.param_change('FRAME4', 'G', 81)
            mprog.param_change('FRAME4', 'H', 14)
            mprog.param_change('FRAME4', 'I', 7)
            mprog.param_change('FRAME4', 'J(a)', 95)
            mprog.activatefeatrue('channel steel', 0)
        elif i== 7:
            mprog.param_change('FRAME4', 'A', 90)
            mprog.param_change('FRAME4', 'B', 1110)
            mprog.param_change('FRAME4', 'D', 300)
            mprog.param_change('FRAME4', 'E', 9)
            mprog.param_change('FRAME4', 'F', 13)
            mprog.param_change('FRAME4', 'G', 81)
            mprog.param_change('FRAME4', 'H', 14)
            mprog.param_change('FRAME4', 'I', 7)
            mprog.param_change('FRAME4', 'J(a)', 95)
            mprog.activatefeatrue('channel steel', 0)
        elif i== 8:
            mprog.param_change('FRAME4', 'A', 100)
            mprog.param_change('FRAME4', 'B', 1178)
            mprog.param_change('FRAME4', 'D', 380)
            mprog.param_change('FRAME4', 'E', 10.5)
            mprog.param_change('FRAME4', 'F', 16)
            mprog.param_change('FRAME4', 'G', 89.5)
            mprog.param_change('FRAME4', 'H', 18)
            mprog.param_change('FRAME4', 'I', 9)
            mprog.param_change('FRAME4', 'J(a)', 95)
            mprog.activatefeatrue('channel steel', 0)
    elif name== 'FRAME10':
        if i== 0:
            mprog.param_change('FRAME10', 'A', 1009)
            mprog.param_change('FRAME10', 'B', 370)
            mprog.param_change('FRAME10', 'C', 415)
            mprog.param_change('FRAME10', 'D', 300)
            mprog.param_change('FRAME10', 'E', 22)
            mprog.param_change('FRAME10', 'F', 393)
            mprog.param_change('FRAME10', 'G', 323)
            mprog.param_change('FRAME10', 'H', 200)
            mprog.param_change('FRAME10', 'I', 52)
            mprog.param_change('FRAME10', 'J', 0)
            mprog.param_change('FRAME10', 'K', 0)
            mprog.param_change('FRAME10', 'L', 0)
            mprog.param_change('FRAME10', 'M', 10)
            mprog.param_change('FRAME10', 'N', 0)
            mprog.param_change('FRAME10', 'N(a)', 0)
            mprog.param_change('FRAME10', 'O', 15)
            mprog.param_change('FRAME10', 'O(a)', 35)
            mprog.param_change('FRAME10', 'P', 15)
            mprog.param_change('FRAME10', 'P(a)', 35)
            mprog.param_change('FRAME10', 'Q', 0)
            mprog.param_change('FRAME10', 'Q(a)', 0)
            mprog.param_change('FRAME10', 'R', 50)
            mprog.param_change('FRAME10', 'S', 20)
            mprog.param_change('FRAME10', 'T', 10)
            mprog.param_change('FRAME10', 'U', 0)
            mprog.param_change('FRAME10', 'V', 0)
            mprog.param_change('FRAME10', 'W', 30)
            mprog.param_change('FRAME10', 'X', 10)
            mprog.param_change('FRAME10', 'Y', 50)
            mprog.param_change('FRAME10', 'Z', 118)
            mprog.param_change('FRAME10', 'AA', 375)
            mprog.param_change('FRAME10', 'AB', 505)
            mprog.param_change('FRAME10', 'AC', 80)
            mprog.param_change('FRAME10', 'AD', 0)
            mprog.param_change('FRAME10', 'AE', 50)
            mprog.param_change('FRAME10', 'AF', 0)
            mprog.param_change('FRAME10', 'AG', 0)
            mprog.param_change('FRAME10', 'AH', 50)
            mprog.activatefeatrue('SN1_2545_Body', 9)
            mprog.activatefeatrue('SN1_2545_X', 0)
        if i == 1:
            mprog.param_change('FRAME10', 'A', 1116)
            mprog.param_change('FRAME10', 'B', 390)
            mprog.param_change('FRAME10', 'C', 483.42)
            mprog.param_change('FRAME10', 'D', 360)
            mprog.param_change('FRAME10', 'E', 55.42)
            mprog.param_change('FRAME10', 'F', 428)
            mprog.param_change('FRAME10', 'G', 337)
            mprog.param_change('FRAME10', 'H', 227)
            mprog.param_change('FRAME10', 'I', 90)
            mprog.param_change('FRAME10', 'J', 0)
            mprog.param_change('FRAME10', 'K', 0)
            mprog.param_change('FRAME10', 'L', 0)
            mprog.param_change('FRAME10', 'M', 10)
            mprog.param_change('FRAME10', 'N', 0)
            mprog.param_change('FRAME10', 'N(a)', 0)
            mprog.param_change('FRAME10', 'O', 15)
            mprog.param_change('FRAME10', 'O(a)', 35)
            mprog.param_change('FRAME10', 'P', 15)
            mprog.param_change('FRAME10', 'P(a)', 35)
            mprog.param_change('FRAME10', 'Q', 0)
            mprog.param_change('FRAME10', 'Q(a)', 0)
            mprog.param_change('FRAME10', 'R', 60)
            mprog.param_change('FRAME10', 'S', 30)
            mprog.param_change('FRAME10', 'T', 10)
            mprog.param_change('FRAME10', 'U', 0)
            mprog.param_change('FRAME10', 'V', 0)
            mprog.param_change('FRAME10', 'W', 20)
            mprog.param_change('FRAME10', 'X', 0)
            mprog.param_change('FRAME10', 'Y', 40)
            mprog.param_change('FRAME10', 'Z', 73)
            mprog.param_change('FRAME10', 'AA', 335)
            mprog.param_change('FRAME10', 'AB', 635)
            mprog.param_change('FRAME10', 'AC', 43)
            mprog.param_change('FRAME10', 'AD', 10)
            mprog.param_change('FRAME10', 'AE', 60)
            mprog.param_change('FRAME10', 'AF', 0)
            mprog.param_change('FRAME10', 'AG', 0)
            mprog.param_change('FRAME10', 'AH', 50)
            mprog.activatefeatrue('SN1_2545_Body', 0)

    elif name== 'FRAME30':
        if i== 0:
            mprog.param_change('FRAME30', 'A', 637)
            mprog.param_change('FRAME30', 'B', 488)
            mprog.param_change('FRAME30', 'C', 29)
            mprog.param_change('FRAME30', 'D', 52)
            mprog.param_change('FRAME30', 'E', 250)
            mprog.param_change('FRAME30', 'F', 250)
            mprog.param_change('FRAME30', 'G', 180)
            mprog.param_change('FRAME30', 'H', 100)
            mprog.param_change('FRAME30', 'I', 15)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 10)
            mprog.param_change('FRAME30', 'J(a)', 45)
            mprog.param_change('FRAME30', 'K', 13)
            mprog.param_change('FRAME30', 'K(a)', 40)
            mprog.param_change('FRAME30', 'L', 10)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 15)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 14)
            mprog.param_change('FRAME30', 'N(a)', 40)
            mprog.param_change('FRAME30', 'O', 28)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 1:
            mprog.param_change('FRAME30', 'A', 728)
            mprog.param_change('FRAME30', 'B', 586)
            mprog.param_change('FRAME30', 'C', 33)
            mprog.param_change('FRAME30', 'D', 52)
            mprog.param_change('FRAME30', 'E', 290)
            mprog.param_change('FRAME30', 'F', 297)
            mprog.param_change('FRAME30', 'G', 190)
            mprog.param_change('FRAME30', 'H', 110)
            mprog.param_change('FRAME30', 'I', 20)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 12)
            mprog.param_change('FRAME30', 'J(a)', 40)
            mprog.param_change('FRAME30', 'K', 15)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 10)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 20)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 16)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 32)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 2:
            mprog.param_change('FRAME30', 'A', 786)
            mprog.param_change('FRAME30', 'B', 626)
            mprog.param_change('FRAME30', 'C', 37)
            mprog.param_change('FRAME30', 'D', 58)
            mprog.param_change('FRAME30', 'E', 305)
            mprog.param_change('FRAME30', 'F', 330)
            mprog.param_change('FRAME30', 'G', 200)
            mprog.param_change('FRAME30', 'H', 115)
            mprog.param_change('FRAME30', 'I', 15)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 14)
            mprog.param_change('FRAME30', 'J(a)', 40)
            mprog.param_change('FRAME30', 'K', 16)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 10)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 15)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 18)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 35)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 3:
            mprog.param_change('FRAME30', 'A', 829)
            mprog.param_change('FRAME30', 'B', 664)
            mprog.param_change('FRAME30', 'C', 48)
            mprog.param_change('FRAME30', 'D', 60)
            mprog.param_change('FRAME30', 'E', 330)
            mprog.param_change('FRAME30', 'F', 348)
            mprog.param_change('FRAME30', 'G', 220)
            mprog.param_change('FRAME30', 'H', 115)
            mprog.param_change('FRAME30', 'I', 15)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 14)
            mprog.param_change('FRAME30', 'J(a)', 40)
            mprog.param_change('FRAME30', 'K', 15)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 12)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 0)
            mprog.param_change('FRAME30', 'M(a)', 0)
            mprog.param_change('FRAME30', 'N', 16)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 32)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 4:
            mprog.param_change('FRAME30', 'A', 888)
            mprog.param_change('FRAME30', 'B', 744)
            mprog.param_change('FRAME30', 'C', 31)
            mprog.param_change('FRAME30', 'D', 65)
            mprog.param_change('FRAME30', 'E', 380)
            mprog.param_change('FRAME30', 'F', 353.5)
            mprog.param_change('FRAME30', 'G', 240)
            mprog.param_change('FRAME30', 'H', 150)
            mprog.param_change('FRAME30', 'I', 23)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 16)
            mprog.param_change('FRAME30', 'J(a)', 35)
            mprog.param_change('FRAME30', 'K', 15)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 16)
            mprog.param_change('FRAME30', 'L(a)', 35)
            mprog.param_change('FRAME30', 'M', 16)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 16)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 32)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 5:
            mprog.param_change('FRAME30', 'A', 1027)
            mprog.param_change('FRAME30', 'B', 850)
            mprog.param_change('FRAME30', 'C', 50)
            mprog.param_change('FRAME30', 'D', 90)
            mprog.param_change('FRAME30', 'E', 420)
            mprog.param_change('FRAME30', 'F', 448)
            mprog.param_change('FRAME30', 'G', 270)
            mprog.param_change('FRAME30', 'H', 160)
            mprog.param_change('FRAME30', 'I', 15)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 20)
            mprog.param_change('FRAME30', 'J(a)', 35)
            mprog.param_change('FRAME30', 'K', 19)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 16)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 0)
            mprog.param_change('FRAME30', 'M(a)', 0)
            mprog.param_change('FRAME30', 'N', 20)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 40)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 6:
            mprog.param_change('FRAME30', 'A', 1191)
            mprog.param_change('FRAME30', 'B', 940)
            mprog.param_change('FRAME30', 'C', 50)
            mprog.param_change('FRAME30', 'D', 105)
            mprog.param_change('FRAME30', 'E', 520)
            mprog.param_change('FRAME30', 'F', 487)
            mprog.param_change('FRAME30', 'G', 310)
            mprog.param_change('FRAME30', 'H', 150)
            mprog.param_change('FRAME30', 'I', 25)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 25)
            mprog.param_change('FRAME30', 'J(a)', 35)
            mprog.param_change('FRAME30', 'K', 24)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 16)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 25)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 25)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 50)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 7:
            mprog.param_change('FRAME30', 'A', 1369)
            mprog.param_change('FRAME30', 'B', 1110)
            mprog.param_change('FRAME30', 'C', 50)
            mprog.param_change('FRAME30', 'D', 105)
            mprog.param_change('FRAME30', 'E', 600)
            mprog.param_change('FRAME30', 'F', 565)
            mprog.param_change('FRAME30', 'G', 320)
            mprog.param_change('FRAME30', 'H', 190)
            mprog.param_change('FRAME30', 'I', 30)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 30)
            mprog.param_change('FRAME30', 'J(a)', 35)
            mprog.param_change('FRAME30', 'K', 29)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 15)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 30)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 23)
            mprog.param_change('FRAME30', 'N(a)', 35)
            mprog.param_change('FRAME30', 'O', 60)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 8:
            mprog.param_change('FRAME30', 'A', 1540)
            mprog.param_change('FRAME30', 'B', 1180)
            mprog.param_change('FRAME30', 'C', 50)
            mprog.param_change('FRAME30', 'D', 105)
            mprog.param_change('FRAME30', 'E', 680)
            mprog.param_change('FRAME30', 'F', 636)
            mprog.param_change('FRAME30', 'G', 340)
            mprog.param_change('FRAME30', 'H', 170)
            mprog.param_change('FRAME30', 'I', 33)
            mprog.param_change('FRAME30', 'I(a)', 35)
            mprog.param_change('FRAME30', 'J', 33)
            mprog.param_change('FRAME30', 'J(a)', 35)
            mprog.param_change('FRAME30', 'K', 32)
            mprog.param_change('FRAME30', 'K(a)', 35)
            mprog.param_change('FRAME30', 'L', 20)
            mprog.param_change('FRAME30', 'L(a)', 45)
            mprog.param_change('FRAME30', 'M', 33)
            mprog.param_change('FRAME30', 'M(a)', 35)
            mprog.param_change('FRAME30', 'N', 0)
            mprog.param_change('FRAME30', 'N(a)', 0)
            mprog.param_change('FRAME30', 'O', 65)
            mprog.activatefeatrue('SN1_25250_Body', 4)
            mprog.activatefeatrue('SN1_25250_M', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
    elif name== 'FRAME34':
        if i==0:
            mprog.param_change('FRAME34', 'A', 38)
            mprog.param_change('FRAME34', 'B', 95)
            mprog.param_change('FRAME34', 'C', 22)
            mprog.param_change('FRAME34', 'D', 55)
            mprog.param_change('FRAME34', 'E', 38)
            mprog.param_change('FRAME34', 'F', 0)
            mprog.param_change('FRAME34', 'F(a)', 0)
            mprog.param_change('FRAME34', 'G', 0)
            mprog.param_change('FRAME34', 'G(a)', 0)
            mprog.param_change('FRAME34', 'H', 0)
            mprog.param_change('FRAME34', 'I', 0)
            mprog.param_change('FRAME34', 'J', 0)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 2)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 25)
            mprog.param_change('FRAME34', 'd', 40)
            mprog.param_change('FRAME34', 'e', 160.7)
            mprog.param_change('FRAME34', 'f', 235)
            mprog.param_change('FRAME34', 'g', 0)
            mprog.param_change('FRAME34', 'h', 0)
            mprog.param_change('FRAME34', 'FRAME9_L', 0)
            mprog.param_change('FRAME34', 'FRAME1', 19)
            mprog.param_change('FRAME34', 'i', 16)
            mprog.activatefeatrue('FRAME_SN1_2545_Body', 0)
            mprog.activatefeatrue('Hole_1_i', 0)
        elif i== 1:
            mprog.param_change('FRAME34', 'A', 34)
            mprog.param_change('FRAME34', 'B', 99)
            mprog.param_change('FRAME34', 'C', 22)
            mprog.param_change('FRAME34', 'D', 75)
            mprog.param_change('FRAME34', 'E', 50)
            mprog.param_change('FRAME34', 'F', 0)
            mprog.param_change('FRAME34', 'F(a)', 0)
            mprog.param_change('FRAME34', 'G', 0)
            mprog.param_change('FRAME34', 'G(a)', 0)
            mprog.param_change('FRAME34', 'H', 0)
            mprog.param_change('FRAME34', 'I', 0)
            mprog.param_change('FRAME34', 'J', 0)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 2)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 50)
            mprog.param_change('FRAME34', 'd', 50)
            mprog.param_change('FRAME34', 'e', 194.44)
            mprog.param_change('FRAME34', 'f', 275)
            mprog.param_change('FRAME34', 'g', 0)
            mprog.param_change('FRAME34', 'h', 0)
            mprog.param_change('FRAME34', 'FRAME9_L', 0)
            mprog.param_change('FRAME34', 'FRAME1', 22)
            mprog.param_change('FRAME34', 'i', 16)
            mprog.activatefeatrue('FRAME_SN1_2545_Body', 0)
            mprog.activatefeatrue('Hole_1_i', 0)
        elif i== 2:
            mprog.param_change('FRAME34', 'A', 34)
            mprog.param_change('FRAME34', 'B', 99)
            mprog.param_change('FRAME34', 'C', 22)
            mprog.param_change('FRAME34', 'D', 75)
            mprog.param_change('FRAME34', 'E', 50)
            mprog.param_change('FRAME34', 'F', 0)
            mprog.param_change('FRAME34', 'F(a)', 0)
            mprog.param_change('FRAME34', 'G', 0)
            mprog.param_change('FRAME34', 'G(a)', 0)
            mprog.param_change('FRAME34', 'H', 0)
            mprog.param_change('FRAME34', 'I', 0)
            mprog.param_change('FRAME34', 'J', 0)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 2)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 50)
            mprog.param_change('FRAME34', 'd', 50)
            mprog.param_change('FRAME34', 'e', 218.5)
            mprog.param_change('FRAME34', 'f', 292)
            mprog.param_change('FRAME34', 'g', 0)
            mprog.param_change('FRAME34', 'h', 0)
            mprog.param_change('FRAME34', 'FRAME9_L', 0)
            mprog.param_change('FRAME34', 'FRAME1', 25)
            mprog.param_change('FRAME34', 'i', 16)
            mprog.activatefeatrue('FRAME_SN1_2545_Body', 0)
            mprog.activatefeatrue('Hole_1_i', 0)
        elif i == 3:
            mprog.param_change('FRAME34', 'A', 50)
            mprog.param_change('FRAME34', 'B', 100)
            mprog.param_change('FRAME34', 'C', 0)
            mprog.param_change('FRAME34', 'D', 0)
            mprog.param_change('FRAME34', 'E', 60)
            mprog.param_change('FRAME34', 'F', 15)
            mprog.param_change('FRAME34', 'F(a)', 45)
            mprog.param_change('FRAME34', 'G', 15)
            mprog.param_change('FRAME34', 'G(a)', 45)
            mprog.param_change('FRAME34', 'H', 0)
            mprog.param_change('FRAME34', 'I', 0)
            mprog.param_change('FRAME34', 'J', 0)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 4)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 25)
            mprog.param_change('FRAME34', 'd', 25)
            mprog.param_change('FRAME34', 'e', 272.24)
            mprog.param_change('FRAME34', 'f', 312)
            mprog.param_change('FRAME34', 'g', 48)
            mprog.param_change('FRAME34', 'h', 16)
            mprog.param_change('FRAME34', 'FRAME9_L', 28)
            mprog.param_change('FRAME34', 'FRAME1', 28)
            mprog.param_change('FRAME34', 'i', 0)
            mprog.activatefeatrue('FRAME_SN1_60_Body', 0)
            mprog.activatefeatrue('Hole_1_h FRAME9_L', 0)
        elif i == 4:
            mprog.param_change('FRAME34', 'A', 35)
            mprog.param_change('FRAME34', 'B', 130)
            mprog.param_change('FRAME34', 'C', 0)
            mprog.param_change('FRAME34', 'D', 0)
            mprog.param_change('FRAME34', 'E', 80)
            mprog.param_change('FRAME34', 'F', 18)
            mprog.param_change('FRAME34', 'F(a)', 45)
            mprog.param_change('FRAME34', 'G', 18)
            mprog.param_change('FRAME34', 'G(a)', 45)
            mprog.param_change('FRAME34', 'H', 100)
            mprog.param_change('FRAME34', 'I', 65)
            mprog.param_change('FRAME34', 'J', 30)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 4)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 30)
            mprog.param_change('FRAME34', 'd', 35)
            mprog.param_change('FRAME34', 'e', 272.24)
            mprog.param_change('FRAME34', 'f', 350)
            mprog.param_change('FRAME34', 'g', 62)
            mprog.param_change('FRAME34', 'h', 16)
            mprog.param_change('FRAME34', 'FRAME9_L', 14)
            mprog.param_change('FRAME34', 'FRAME1', 45)
            mprog.param_change('FRAME34', 'i', 0)
            mprog.activatefeatrue('FRAME_SN1_80110_Body', 0)
            mprog.activatefeatrue('Hole_1_h FRAME9_L', 0)
        elif i == 5:
            mprog.param_change('FRAME34', 'A', 40)
            mprog.param_change('FRAME34', 'B', 182)
            mprog.param_change('FRAME34', 'C', 0)
            mprog.param_change('FRAME34', 'D', 0)
            mprog.param_change('FRAME34', 'E', 80)
            mprog.param_change('FRAME34', 'F', 20)
            mprog.param_change('FRAME34', 'F(a)', 45)
            mprog.param_change('FRAME34', 'G', 0)
            mprog.param_change('FRAME34', 'G(a)', 0)
            mprog.param_change('FRAME34', 'H', 152)
            mprog.param_change('FRAME34', 'I', 110)
            mprog.param_change('FRAME34', 'J', 30)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 4)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 30)
            mprog.param_change('FRAME34', 'd', 30)
            mprog.param_change('FRAME34', 'e', 272.24)
            mprog.param_change('FRAME34', 'f', 325)
            mprog.param_change('FRAME34', 'g', 150)
            mprog.param_change('FRAME34', 'h', 16)
            mprog.param_change('FRAME34', 'FRAME9_L', 18)
            mprog.param_change('FRAME34', 'FRAME1', 50)
            mprog.param_change('FRAME34', 'i', 0)
            mprog.activatefeatrue('FRAME_SN1_80110_Body', 0)
            mprog.activatefeatrue('Hole_1_h FRAME9_L', 0)
        elif i == 7:
            mprog.param_change('FRAME34', 'B', 130)
            mprog.param_change('FRAME34', 'C', 0)
            mprog.param_change('FRAME34', 'D', 0)
            mprog.param_change('FRAME34', 'E', 80)
            mprog.param_change('FRAME34', 'F', 20)
            mprog.param_change('FRAME34', 'F(a)', 45)
            mprog.param_change('FRAME34', 'G', 20)
            mprog.param_change('FRAME34', 'G(a)', 45)
            mprog.param_change('FRAME34', 'H', 0)
            mprog.param_change('FRAME34', 'I', 0)
            mprog.param_change('FRAME34', 'J', 0)
            mprog.param_change('FRAME34', 'K', 10)
            mprog.param_change('FRAME34', 'a', 4)
            mprog.param_change('FRAME34', 'b', 'M16')
            mprog.param_change('FRAME34', 'c', 30)
            mprog.param_change('FRAME34', 'd', 30)
            mprog.param_change('FRAME34', 'e', 470)
            mprog.param_change('FRAME34', 'f', 555)
            mprog.param_change('FRAME34', 'g', 60)
            mprog.param_change('FRAME34', 'h', 15)
            mprog.param_change('FRAME34', 'FRAME9_L', 25)
            mprog.param_change('FRAME34', 'FRAME1', 60)
            mprog.param_change('FRAME34', 'i', 0)
            mprog.activatefeatrue('FRAME_SN1_200_Body', 0)
            mprog.activatefeatrue('Hole_1_h FRAME9_L', 0)
        elif i == 8:
            mprog.param_change('FRAME34', 'A', 50)
            mprog.param_change('FRAME34', 'B', 69)
            mprog.param_change('FRAME34', 'C', 0)
            mprog.param_change('FRAME34', 'D', 0)
            mprog.param_change('FRAME34', 'E', 0)
            mprog.param_change('FRAME34', 'F', 0)
            mprog.param_change('FRAME34', 'F(a)', 0)
            mprog.param_change('FRAME34', 'G', 0)
            mprog.param_change('FRAME34', 'G(a)', 0)
            mprog.param_change('FRAME34', 'H', 0)
            mprog.param_change('FRAME34', 'I', 0)
            mprog.param_change('FRAME34', 'J', 0)
            mprog.param_change('FRAME34', 'K', 0)
            mprog.param_change('FRAME34', 'a', 0)
            mprog.param_change('FRAME34', 'b', 0)
            mprog.param_change('FRAME34', 'c', 32)
            mprog.param_change('FRAME34', 'd', 32)
            mprog.param_change('FRAME34', 'e', 315)
            mprog.param_change('FRAME34', 'f', 0)
            mprog.param_change('FRAME34', 'g', 0)
            mprog.param_change('FRAME34', 'h', 0)
            mprog.param_change('FRAME34', 'FRAME9_L', 0)
            mprog.param_change('FRAME34', 'FRAME1', 65)
            mprog.param_change('FRAME34', 'i', 0)
            mprog.activatefeatrue('SN1_250_Body', 0)
            mprog.activatefeatrue('Hole_1_B', 0)
    elif name== 'FRAME44':
        if i== 0:
            mprog.param_change('FRAME44', 'A', 647)
            mprog.param_change('FRAME44', 'B', 488)
            mprog.param_change('FRAME44', 'C', 39)
            mprog.param_change('FRAME44', 'D', 52)
            mprog.param_change('FRAME44', 'E', 15)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 10)
            mprog.param_change('FRAME44', 'F(a)', 45)
            mprog.param_change('FRAME44', 'G', 15)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 10)
            mprog.param_change('FRAME44', 'H(a)', 45)
            mprog.param_change('FRAME44', 'I', 9)
            mprog.param_change('FRAME44', 'I(a)', 45)
            mprog.param_change('FRAME44', 'J', 9)
            mprog.param_change('FRAME44', 'J(a)', 45)
            mprog.param_change('FRAME44', 'K', 19)
            mprog.param_change('FRAME44', 'a', 500)
            mprog.param_change('FRAME44', 'b', 240)
            mprog.param_change('FRAME44', 'c', 320)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 0)
            mprog.param_change('FRAME44', 'g', 0)
            mprog.param_change('FRAME44', 'h', 0)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 0)
            mprog.param_change('FRAME44', 'k', 0)
            mprog.param_change('FRAME44', 'l', 0)
            mprog.param_change('FRAME44', 'm', 0)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 3)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 1:
            mprog.param_change('FRAME44', 'A', 837)
            mprog.param_change('FRAME44', 'B', 586)
            mprog.param_change('FRAME44', 'C', 43)
            mprog.param_change('FRAME44', 'D', 52)
            mprog.param_change('FRAME44', 'E', 20)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 12)
            mprog.param_change('FRAME44', 'F(a)', 40)
            mprog.param_change('FRAME44', 'G', 20)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 14)
            mprog.param_change('FRAME44', 'H(a)', 40)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 16)
            mprog.param_change('FRAME44', 'J(a)', 35)
            mprog.param_change('FRAME44', 'K', 25)
            mprog.param_change('FRAME44', 'a', 587)
            mprog.param_change('FRAME44', 'b', 200)
            mprog.param_change('FRAME44', 'c', 420)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 0)
            mprog.param_change('FRAME44', 'g', 0)
            mprog.param_change('FRAME44', 'h', 0)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 0)
            mprog.param_change('FRAME44', 'k', 0)
            mprog.param_change('FRAME44', 'l', 0)
            mprog.param_change('FRAME44', 'm', 0)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 2)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 2:
            mprog.param_change('FRAME44', 'A', 796)
            mprog.param_change('FRAME44', 'B', 626)
            mprog.param_change('FRAME44', 'C', 47)
            mprog.param_change('FRAME44', 'D', 58)
            mprog.param_change('FRAME44', 'E', 15)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 14)
            mprog.param_change('FRAME44', 'F(a)', 40)
            mprog.param_change('FRAME44', 'G', 15)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 14)
            mprog.param_change('FRAME44', 'H(a)', 40)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 25)
            mprog.param_change('FRAME44', 'a', 635)
            mprog.param_change('FRAME44', 'b', 230)
            mprog.param_change('FRAME44', 'c', 440)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 0)
            mprog.param_change('FRAME44', 'g', 0)
            mprog.param_change('FRAME44', 'h', 0)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 0)
            mprog.param_change('FRAME44', 'k', 0)
            mprog.param_change('FRAME44', 'l', 0)
            mprog.param_change('FRAME44', 'm', 0)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 3:
            mprog.param_change('FRAME44', 'A', 829)
            mprog.param_change('FRAME44', 'B', 664)
            mprog.param_change('FRAME44', 'C', 48)
            mprog.param_change('FRAME44', 'D', 60)
            mprog.param_change('FRAME44', 'E', 15)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 13)
            mprog.param_change('FRAME44', 'F(a)', 40)
            mprog.param_change('FRAME44', 'G', 20)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 13)
            mprog.param_change('FRAME44', 'H(a)', 40)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 25)
            mprog.param_change('FRAME44', 'a', 678)
            mprog.param_change('FRAME44', 'b', 230)
            mprog.param_change('FRAME44', 'c', 478)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 50)
            mprog.param_change('FRAME44', 'g', 423)
            mprog.param_change('FRAME44', 'h', 272)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 0)
            mprog.param_change('FRAME44', 'k', 0)
            mprog.param_change('FRAME44', 'l', 11)
            mprog.param_change('FRAME44', 'm', 0)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
            mprog.activatefeatrue('Hole_3', 2)
        elif i== 4:
            mprog.param_change('FRAME44', 'A', 905)
            mprog.param_change('FRAME44', 'B', 744)
            mprog.param_change('FRAME44', 'C', 48)
            mprog.param_change('FRAME44', 'D', 65)
            mprog.param_change('FRAME44', 'E', 23)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 13)
            mprog.param_change('FRAME44', 'F(a)', 40)
            mprog.param_change('FRAME44', 'G', 13)
            mprog.param_change('FRAME44', 'G(a)', 40)
            mprog.param_change('FRAME44', 'H', 13)
            mprog.param_change('FRAME44', 'H(a)', 40)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 25)
            mprog.param_change('FRAME44', 'a', 733.5)
            mprog.param_change('FRAME44', 'b', 230)
            mprog.param_change('FRAME44', 'c', 533.5)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 50)
            mprog.param_change('FRAME44', 'g', 443.5)
            mprog.param_change('FRAME44', 'h', 272)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 70)
            mprog.param_change('FRAME44', 'k', 525)
            mprog.param_change('FRAME44', 'l', 10)
            mprog.param_change('FRAME44', 'm', 0)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
            mprog.activatefeatrue('Hole_3', 2)
            mprog.activatefeatrue('Hole_4', 0)
        elif i== 5:
            mprog.param_change('FRAME44', 'A', 1050)
            mprog.param_change('FRAME44', 'B', 850)
            mprog.param_change('FRAME44', 'C', 73)
            mprog.param_change('FRAME44', 'D', 90)
            mprog.param_change('FRAME44', 'E', 15)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 16)
            mprog.param_change('FRAME44', 'F(a)', 35)
            mprog.param_change('FRAME44', 'G', 16)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 16)
            mprog.param_change('FRAME44', 'H(a)', 35)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 32)
            mprog.param_change('FRAME44', 'a', 868)
            mprog.param_change('FRAME44', 'b', 230)
            mprog.param_change('FRAME44', 'c', 668)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 50)
            mprog.param_change('FRAME44', 'g', 454)
            mprog.param_change('FRAME44', 'h', 272)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 70)
            mprog.param_change('FRAME44', 'k', 630)
            mprog.param_change('FRAME44', 'l', 11)
            mprog.param_change('FRAME44', 'm', 8.5)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
            mprog.activatefeatrue('Hole_3', 2)
            mprog.activatefeatrue('Hole_4', 0)
        elif i== 6:
            mprog.param_change('FRAME44', 'A', 1191)
            mprog.param_change('FRAME44', 'B', 940)
            mprog.param_change('FRAME44', 'C', 50)
            mprog.param_change('FRAME44', 'D', 105)
            mprog.param_change('FRAME44', 'E', 25)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 19)
            mprog.param_change('FRAME44', 'F(a)', 35)
            mprog.param_change('FRAME44', 'G', 19)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 19)
            mprog.param_change('FRAME44', 'H(a)', 35)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 38)
            mprog.param_change('FRAME44', 'a', 1007)
            mprog.param_change('FRAME44', 'b', 280)
            mprog.param_change('FRAME44', 'c', 807)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 60)
            mprog.param_change('FRAME44', 'g', 654)
            mprog.param_change('FRAME44', 'h', 395)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 70)
            mprog.param_change('FRAME44', 'k', 671)
            mprog.param_change('FRAME44', 'l', 0)
            mprog.param_change('FRAME44', 'm', 8.5)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
            mprog.activatefeatrue('Hole_3', 2)
            mprog.activatefeatrue('Hole_4', 0)
        elif i== 7:
            mprog.param_change('FRAME44', 'A', 1390)
            mprog.param_change('FRAME44', 'B', 1110)
            mprog.param_change('FRAME44', 'C', 71)
            mprog.param_change('FRAME44', 'D', 105)
            mprog.param_change('FRAME44', 'E', 30)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 23)
            mprog.param_change('FRAME44', 'F(a)', 35)
            mprog.param_change('FRAME44', 'G', 23)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 23)
            mprog.param_change('FRAME44', 'H(a)', 35)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 45)
            mprog.param_change('FRAME44', 'a', 1165)
            mprog.param_change('FRAME44', 'b', 280)
            mprog.param_change('FRAME44', 'c', 965)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 60)
            mprog.param_change('FRAME44', 'g', 790)
            mprog.param_change('FRAME44', 'h', 470)
            mprog.param_change('FRAME44', 'i', 0)
            mprog.param_change('FRAME44', 'j', 70)
            mprog.param_change('FRAME44', 'k', 790)
            mprog.param_change('FRAME44', 'l', 0)
            mprog.param_change('FRAME44', 'm', 8.5)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
            mprog.activatefeatrue('Hole_3', 2)
            mprog.activatefeatrue('Hole_4', 0)
        elif i== 8:
            mprog.param_change('FRAME44', 'A', 1680)
            mprog.param_change('FRAME44', 'B', 1180)
            mprog.param_change('FRAME44', 'C', 190)
            mprog.param_change('FRAME44', 'D', 105)
            mprog.param_change('FRAME44', 'E', 33)
            mprog.param_change('FRAME44', 'E(a)', 35)
            mprog.param_change('FRAME44', 'F', 23)
            mprog.param_change('FRAME44', 'F(a)', 35)
            mprog.param_change('FRAME44', 'G', 23)
            mprog.param_change('FRAME44', 'G(a)', 35)
            mprog.param_change('FRAME44', 'H', 23)
            mprog.param_change('FRAME44', 'H(a)', 35)
            mprog.param_change('FRAME44', 'I', 0)
            mprog.param_change('FRAME44', 'I(a)', 0)
            mprog.param_change('FRAME44', 'J', 0)
            mprog.param_change('FRAME44', 'J(a)', 0)
            mprog.param_change('FRAME44', 'K', 45)
            mprog.param_change('FRAME44', 'a', 1316)
            mprog.param_change('FRAME44', 'b', 280)
            mprog.param_change('FRAME44', 'c', 1116)
            mprog.param_change('FRAME44', 'd', 'RC1 / 8')
            mprog.param_change('FRAME44', 'd(D)', 8.566)
            mprog.param_change('FRAME44', 'd(P)', 0.907)
            mprog.param_change('FRAME44', 'f', 50)
            mprog.param_change('FRAME44', 'g', 679)
            mprog.param_change('FRAME44', 'h', 315)
            mprog.param_change('FRAME44', 'i', 49)
            mprog.param_change('FRAME44', 'j', 70)
            mprog.param_change('FRAME44', 'k', 1000)
            mprog.param_change('FRAME44', 'l', 0)
            mprog.param_change('FRAME44', 'm', 8.5)
            mprog.activatefeatrue('SN1_25250_Body', 0)
            mprog.activatefeatrue('Hole_1', 1)
            mprog.activatefeatrue('Hole_2', 0)
            mprog.activatefeatrue('Hole_3', 4)
            mprog.activatefeatrue('Hole_4', 0)
    elif name== 'FRAME48':
        if i== 0:
            mprog.param_change('FRAME48', 'A', 683)
            mprog.param_change('FRAME48', 'B', 251)
            mprog.param_change('FRAME48', 'C', 363)
            mprog.param_change('FRAME48', 'D', 320)
            mprog.param_change('FRAME48', 'E', 216)
            mprog.param_change('FRAME48', 'F', 35)
            mprog.param_change('FRAME48', 'G', 90)
            mprog.param_change('FRAME48', 'H', 60)
            mprog.param_change('FRAME48', 'I', 65)
            mprog.param_change('FRAME48', 'J', 6)
            mprog.param_change('FRAME48', 'J(a)', 45)
            mprog.param_change('FRAME48', 'K', 12)
            mprog.param_change('FRAME48', 'a', 0)
            mprog.param_change('FRAME48', 'b', 0)
            mprog.param_change('FRAME48', 'c', 0)
            mprog.activatefeatrue('SN1_2560_body', 0)
            mprog.activatefeatrue('Hole', 0)
        elif i== 1:
            mprog.param_change('FRAME48', 'A', 662)
            mprog.param_change('FRAME48', 'B', 257)
            mprog.param_change('FRAME48', 'C', 282)
            mprog.param_change('FRAME48', 'D', 380)
            mprog.param_change('FRAME48', 'E', 222)
            mprog.param_change('FRAME48', 'F', 35)
            mprog.param_change('FRAME48', 'G', 87)
            mprog.param_change('FRAME48', 'H', 60)
            mprog.param_change('FRAME48', 'I', 65)
            mprog.param_change('FRAME48', 'J', 6)
            mprog.param_change('FRAME48', 'J(a)', 45)
            mprog.param_change('FRAME48', 'K', 12)
            mprog.param_change('FRAME48', 'a', 0)
            mprog.param_change('FRAME48', 'b', 0)
            mprog.param_change('FRAME48', 'c', 0)
            mprog.activatefeatrue('SN1_2560_body', 0)
            mprog.activatefeatrue('Hole', 0)
        elif i == 2:
            mprog.param_change('FRAME48', 'A', 643)
            mprog.param_change('FRAME48', 'B', 292)
            mprog.param_change('FRAME48', 'C', 323)
            mprog.param_change('FRAME48', 'D', 320)
            mprog.param_change('FRAME48', 'E', 254)
            mprog.param_change('FRAME48', 'F', 38)
            mprog.param_change('FRAME48', 'G', 90)
            mprog.param_change('FRAME48', 'H', 60)
            mprog.param_change('FRAME48', 'I', 65)
            mprog.param_change('FRAME48', 'J', 6)
            mprog.param_change('FRAME48', 'J(a)', 45)
            mprog.param_change('FRAME48', 'K', 16)
            mprog.param_change('FRAME48', 'a', 0)
            mprog.param_change('FRAME48', 'b', 0)
            mprog.param_change('FRAME48', 'c', 0)
            mprog.activatefeatrue('SN1_2560_body', 0)
            mprog.activatefeatrue('Hole', 0)
        elif i == 3:
            mprog.param_change('FRAME48', 'A', 731)
            mprog.param_change('FRAME48', 'B', 254)
            mprog.param_change('FRAME48', 'C', 0)
            mprog.param_change('FRAME48', 'D', 0)
            mprog.param_change('FRAME48', 'E', 0)
            mprog.param_change('FRAME48', 'F', 0)
            mprog.param_change('FRAME48', 'G', 90)
            mprog.param_change('FRAME48', 'H', 52)
            mprog.param_change('FRAME48', 'I', 65)
            mprog.param_change('FRAME48', 'J', 0)
            mprog.param_change('FRAME48', 'J(a)', 0)
            mprog.param_change('FRAME48', 'K', 28)
            mprog.param_change('FRAME48', 'a', 0)
            mprog.param_change('FRAME48', 'b', 0)
            mprog.param_change('FRAME48', 'c', 0)
            mprog.activatefeatrue('SN1_2560_body', 1)
            mprog.activatefeatrue('Hole', 0)
        elif i== 4:
            mprog.param_change('FRAME48', 'A', 61)
            mprog.param_change('FRAME48', 'B', 28)
            mprog.param_change('FRAME48', 'C', 0)
            mprog.param_change('FRAME48', 'D', 0)
            mprog.param_change('FRAME48', 'E', 0)
            mprog.param_change('FRAME48', 'F', 0)
            mprog.param_change('FRAME48', 'G', 0)
            mprog.param_change('FRAME48', 'H', 0)
            mprog.param_change('FRAME48', 'I', 0)
            mprog.param_change('FRAME48', 'J', 0)
            mprog.param_change('FRAME48', 'J(a)', 0)
            mprog.param_change('FRAME48', 'K', 0)
            mprog.param_change('FRAME48', 'a', 'M12')
            mprog.param_change('FRAME48', 'b', 45)
            mprog.param_change('FRAME48', 'c', 58)
            mprog.activatefeatrue('SN1_80250_body', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 5:
            mprog.param_change('FRAME48', 'A', 85)
            mprog.param_change('FRAME48', 'B', 32)
            mprog.param_change('FRAME48', 'C', 0)
            mprog.param_change('FRAME48', 'D', 0)
            mprog.param_change('FRAME48', 'E', 0)
            mprog.param_change('FRAME48', 'F', 0)
            mprog.param_change('FRAME48', 'G', 0)
            mprog.param_change('FRAME48', 'H', 0)
            mprog.param_change('FRAME48', 'I', 0)
            mprog.param_change('FRAME48', 'J', 0)
            mprog.param_change('FRAME48', 'J(a)', 0)
            mprog.param_change('FRAME48', 'K', 0)
            mprog.param_change('FRAME48', 'a', 'M12')
            mprog.param_change('FRAME48', 'b', 62)
            mprog.param_change('FRAME48', 'c', 82)
            mprog.activatefeatrue('SN1_80250_body', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 6:
            mprog.param_change('FRAME48', 'A', 75)
            mprog.param_change('FRAME48', 'B', 32)
            mprog.param_change('FRAME48', 'C', 0)
            mprog.param_change('FRAME48', 'D', 0)
            mprog.param_change('FRAME48', 'E', 0)
            mprog.param_change('FRAME48', 'F', 0)
            mprog.param_change('FRAME48', 'G', 0)
            mprog.param_change('FRAME48', 'H', 0)
            mprog.param_change('FRAME48', 'I', 0)
            mprog.param_change('FRAME48', 'J', 0)
            mprog.param_change('FRAME48', 'J(a)', 0)
            mprog.param_change('FRAME48', 'K', 0)
            mprog.param_change('FRAME48', 'a', 'M12')
            mprog.param_change('FRAME48', 'b', 52)
            mprog.param_change('FRAME48', 'c', 75)
            mprog.activatefeatrue('SN1_80250_body', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 7:
            mprog.param_change('FRAME48', 'A', 95)
            mprog.param_change('FRAME48', 'B', 32)
            mprog.param_change('FRAME48', 'C', 0)
            mprog.param_change('FRAME48', 'D', 0)
            mprog.param_change('FRAME48', 'E', 0)
            mprog.param_change('FRAME48', 'F', 0)
            mprog.param_change('FRAME48', 'G', 0)
            mprog.param_change('FRAME48', 'H', 0)
            mprog.param_change('FRAME48', 'I', 0)
            mprog.param_change('FRAME48', 'J', 0)
            mprog.param_change('FRAME48', 'J(a)', 0)
            mprog.param_change('FRAME48', 'K', 0)
            mprog.param_change('FRAME48', 'a', 'M12')
            mprog.param_change('FRAME48', 'b', 72)
            mprog.param_change('FRAME48', 'c', 92)
            mprog.activatefeatrue('SN1_80250_body', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i== 8:
            mprog.param_change('FRAME48', 'A', 95)
            mprog.param_change('FRAME48', 'B', 32)
            mprog.param_change('FRAME48', 'C', 0)
            mprog.param_change('FRAME48', 'D', 0)
            mprog.param_change('FRAME48', 'E', 0)
            mprog.param_change('FRAME48', 'F', 0)
            mprog.param_change('FRAME48', 'G', 0)
            mprog.param_change('FRAME48', 'H', 0)
            mprog.param_change('FRAME48', 'I', 0)
            mprog.param_change('FRAME48', 'J', 0)
            mprog.param_change('FRAME48', 'J(a)', 0)
            mprog.param_change('FRAME48', 'K', 0)
            mprog.param_change('FRAME48', 'a', 'M12')
            mprog.param_change('FRAME48', 'b', 72)
            mprog.param_change('FRAME48', 'c', 92)
            mprog.activatefeatrue('SN1_80250_body', 0)
            mprog.activatefeatrue('Hole_2', 0)
    elif name== 'FRAME49':
        if i== 0:
            mprog.param_change('FRAME49', 'A', 683)
            mprog.param_change('FRAME49', 'B', 251)
            mprog.param_change('FRAME49', 'C', 216)
            mprog.param_change('FRAME49', 'D', 363)
            mprog.param_change('FRAME49', 'E', 90)
            mprog.param_change('FRAME49', 'F', 202)
            mprog.param_change('FRAME49', 'G', 240)
            mprog.param_change('FRAME49', 'H', 60)
            mprog.param_change('FRAME49', 'I', 86)
            mprog.param_change('FRAME49', 'J', 5)
            mprog.param_change('FRAME49', 'K', 65)
            mprog.param_change('FRAME49', 'L', 6)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 12)
            mprog.param_change('FRAME49', 'L(a)', 45)
            mprog.param_change('FRAME49', 'a', 0)
            mprog.param_change('FRAME49', 'b', 0)
            mprog.param_change('FRAME49', 'c', 0)
            mprog.activatefeatrue('SN1_2545_Body', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 1:
            mprog.param_change('FRAME49', 'A', 692)
            mprog.param_change('FRAME49', 'B', 257)
            mprog.param_change('FRAME49', 'C', 222)
            mprog.param_change('FRAME49', 'D', 282)
            mprog.param_change('FRAME49', 'E', 87)
            mprog.param_change('FRAME49', 'F', 199)
            mprog.param_change('FRAME49', 'G', 240)
            mprog.param_change('FRAME49', 'H', 60)
            mprog.param_change('FRAME49', 'I', 90)
            mprog.param_change('FRAME49', 'J', 5)
            mprog.param_change('FRAME49', 'K', 65)
            mprog.param_change('FRAME49', 'L', 6)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 12)
            mprog.param_change('FRAME49', 'L(a)', 45)
            mprog.param_change('FRAME49', 'a', 0)
            mprog.param_change('FRAME49', 'b', 0)
            mprog.param_change('FRAME49', 'c', 0)
            mprog.activatefeatrue('SN1_2545_Body', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 0)
        elif i == 2:
            mprog.param_change('FRAME49', 'A', 643)
            mprog.param_change('FRAME49', 'B', 292)
            mprog.param_change('FRAME49', 'C', 254)
            mprog.param_change('FRAME49', 'D', 323)
            mprog.param_change('FRAME49', 'E', 90)
            mprog.param_change('FRAME49', 'F', 202)
            mprog.param_change('FRAME49', 'G', 240)
            mprog.param_change('FRAME49', 'H', 60)
            mprog.param_change('FRAME49', 'I', 86)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 65)
            mprog.param_change('FRAME49', 'L', 6)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 16)
            mprog.param_change('FRAME49', 'L(a)', 45)
            mprog.param_change('FRAME49', 'a', 0)
            mprog.param_change('FRAME49', 'b', 0)
            mprog.param_change('FRAME49', 'c', 0)
            mprog.activatefeatrue('SN1_2545_Body', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 1)
        elif i == 3:
            mprog.param_change('FRAME49', 'A', 731)
            mprog.param_change('FRAME49', 'B', 254)
            mprog.param_change('FRAME49', 'C', 0)
            mprog.param_change('FRAME49', 'D', 265)
            mprog.param_change('FRAME49', 'E', 90)
            mprog.param_change('FRAME49', 'F', 239)
            mprog.param_change('FRAME49', 'G', 202)
            mprog.param_change('FRAME49', 'H', 52)
            mprog.param_change('FRAME49', 'I', 86)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 65)
            mprog.param_change('FRAME49', 'L', 10)
            mprog.param_change('FRAME49', 'M', 60)
            mprog.param_change('FRAME49', 'N', 75)
            mprog.param_change('FRAME49', 'O', 28)
            mprog.param_change('FRAME49', 'L(a)', 45)
            mprog.param_change('FRAME49', 'a', 0)
            mprog.param_change('FRAME49', 'b', 0)
            mprog.param_change('FRAME49', 'c', 0)
            mprog.activatefeatrue('SN1_60_Body', 0)
            mprog.activatefeatrue('Hole_1', 0)
            mprog.activatefeatrue('Hole_2', 1)
        elif i == 4:
            mprog.param_change('FRAME49', 'A', 45)
            mprog.param_change('FRAME49', 'B', 30)
            mprog.param_change('FRAME49', 'C', 0)
            mprog.param_change('FRAME49', 'D', 0)
            mprog.param_change('FRAME49', 'E', 0)
            mprog.param_change('FRAME49', 'F', 0)
            mprog.param_change('FRAME49', 'G', 0)
            mprog.param_change('FRAME49', 'H', 0)
            mprog.param_change('FRAME49', 'I', 0)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 0)
            mprog.param_change('FRAME49', 'L', 0)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 0)
            mprog.param_change('FRAME49', 'L(a)', 0)
            mprog.param_change('FRAME49', 'a', 'M16')
            mprog.param_change('FRAME49', 'b', 30)
            mprog.param_change('FRAME49', 'c', 37)
            mprog.activatefeatrue('SN1_80250_Body', 0)
            mprog.activatefeatrue('Hole_3', 0)
        elif i == 5:
            mprog.param_change('FRAME49', 'A', 62)
            mprog.param_change('FRAME49', 'B', 30)
            mprog.param_change('FRAME49', 'C', 0)
            mprog.param_change('FRAME49', 'D', 0)
            mprog.param_change('FRAME49', 'E', 0)
            mprog.param_change('FRAME49', 'F', 0)
            mprog.param_change('FRAME49', 'G', 0)
            mprog.param_change('FRAME49', 'H', 0)
            mprog.param_change('FRAME49', 'I', 0)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 0)
            mprog.param_change('FRAME49', 'L', 0)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 0)
            mprog.param_change('FRAME49', 'L(a)', 0)
            mprog.param_change('FRAME49', 'a', 'M16')
            mprog.param_change('FRAME49', 'b', 30)
            mprog.param_change('FRAME49', 'c', 54)
            mprog.activatefeatrue('SN1_80250_Body', 0)
            mprog.activatefeatrue('Hole_3', 0)
        elif i== 6:
            mprog.param_change('FRAME49', 'A', 50)
            mprog.param_change('FRAME49', 'B', 30)
            mprog.param_change('FRAME49', 'C', 0)
            mprog.param_change('FRAME49', 'D', 0)
            mprog.param_change('FRAME49', 'E', 0)
            mprog.param_change('FRAME49', 'F', 0)
            mprog.param_change('FRAME49', 'G', 0)
            mprog.param_change('FRAME49', 'H', 0)
            mprog.param_change('FRAME49', 'I', 0)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 0)
            mprog.param_change('FRAME49', 'L', 0)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 0)
            mprog.param_change('FRAME49', 'L(a)', 0)
            mprog.param_change('FRAME49', 'a', 'M16')
            mprog.param_change('FRAME49', 'b', 30)
            mprog.param_change('FRAME49', 'c', 44)
            mprog.activatefeatrue('SN1_80250_Body', 0)
            mprog.activatefeatrue('Hole_3', 0)
        elif i== 7:
            mprog.param_change('FRAME49', 'A', 72)
            mprog.param_change('FRAME49', 'B', 30)
            mprog.param_change('FRAME49', 'C', 0)
            mprog.param_change('FRAME49', 'D', 0)
            mprog.param_change('FRAME49', 'E', 0)
            mprog.param_change('FRAME49', 'F', 0)
            mprog.param_change('FRAME49', 'G', 0)
            mprog.param_change('FRAME49', 'H', 0)
            mprog.param_change('FRAME49', 'I', 0)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 0)
            mprog.param_change('FRAME49', 'L', 0)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 0)
            mprog.param_change('FRAME49', 'L(a)', 0)
            mprog.param_change('FRAME49', 'a', 'M16')
            mprog.param_change('FRAME49', 'b', 30)
            mprog.param_change('FRAME49', 'c', 64)
            mprog.activatefeatrue('SN1_80250_Body', 0)
            mprog.activatefeatrue('Hole_3', 0)
        elif i == 8:
            mprog.param_change('FRAME49', 'A', 72)
            mprog.param_change('FRAME49', 'B', 30)
            mprog.param_change('FRAME49', 'C', 0)
            mprog.param_change('FRAME49', 'D', 0)
            mprog.param_change('FRAME49', 'E', 0)
            mprog.param_change('FRAME49', 'F', 0)
            mprog.param_change('FRAME49', 'G', 0)
            mprog.param_change('FRAME49', 'H', 0)
            mprog.param_change('FRAME49', 'I', 0)
            mprog.param_change('FRAME49', 'J', 0)
            mprog.param_change('FRAME49', 'K', 0)
            mprog.param_change('FRAME49', 'L', 0)
            mprog.param_change('FRAME49', 'M', 0)
            mprog.param_change('FRAME49', 'N', 0)
            mprog.param_change('FRAME49', 'O', 0)
            mprog.param_change('FRAME49', 'L(a)', 0)
            mprog.param_change('FRAME49', 'a', 'M16')
            mprog.param_change('FRAME49', 'b', 30)
            mprog.param_change('FRAME49', 'c', 64)
            mprog.activatefeatrue('SN1_80250_Body', 0)
            mprog.activatefeatrue('Hole_3', 0)




change_parameter2('FRAME10', 1)



