import win32com.client as win32
import main_program as mprog
import excel_parameter_change as epc
import time

# 母檔變數變換
def change_parameter(name, i):
    if name == 'FRAME1':
        excel = epc.ExcelOp('FRAME1')
        try:
            FRAME1_parameter_name, FRAME1_parameter_value = excel.part_parameter('FRAME1', i)
            print('FRAME1 Parameter change success')
        except:
            print('FRAME1 Parameter change error')
        try:
            if i == 0:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('AA2')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('VV2')
                mprog.partbodyfeatureactivate('VV4')
                mprog.partbodyfeatureactivate('R倒角')
                mprog.partbodyfeatureactivate('R倒角填料_1')
                mprog.partbodyfeatureactivate('R倒角填料_2')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('小噸數E倒角_B')
                mprog.partbodyfeatureactivate('小噸數Y倒角_B1')
                mprog.partbodyfeatureactivate('喉口倒角_B')
                mprog.partbodyfeatureactivate('喉口倒角補料_B')
                mprog.partbodyfeatureactivate('喉口倒角_B_圓角')
                mprog.activatefeature('110通孔', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 5)
                mprog.activatefeature('5-M5X10L(配管用)', 2)
                mprog.activatefeature('兩點組合', 0)
            elif i == 1:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('AA2')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('VV2')
                mprog.partbodyfeatureactivate('VV4')
                mprog.partbodyfeatureactivate('R倒角')
                mprog.partbodyfeatureactivate('R倒角填料_1')
                mprog.partbodyfeatureactivate('R倒角填料_2')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('小噸數E倒角_B')
                mprog.partbodyfeatureactivate('小噸數Y倒角_B1')
                mprog.partbodyfeatureactivate('喉口倒角_B')
                mprog.partbodyfeatureactivate('喉口倒角補料_B')
                mprog.partbodyfeatureactivate('喉口倒角_B_圓角')
                mprog.activatefeature('110通孔', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 5)
                mprog.activatefeature('5-M5X10L(配管用)', 3)
                mprog.activatefeature('兩點組合', 0)
            elif i == 2:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('AA2')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('VV2')
                mprog.partbodyfeatureactivate('VV4')
                mprog.partbodyfeatureactivate('R倒角')
                mprog.partbodyfeatureactivate('R倒角填料_1')
                mprog.partbodyfeatureactivate('R倒角填料_2')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('小噸數E倒角_B')
                mprog.partbodyfeatureactivate('小噸數Y倒角_B1')
                mprog.partbodyfeatureactivate('喉口倒角_B')
                mprog.partbodyfeatureactivate('喉口倒角補料_B')
                mprog.partbodyfeatureactivate('喉口倒角_B_圓角')
                mprog.activatefeature('110通孔', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 5)
                mprog.activatefeature('5-M5X10L(配管用)', 2)
                mprog.activatefeature('兩點組合', 0)
            elif i == 3:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('AA2')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('V1')
                mprog.partbodyfeatureactivate('V3')
                mprog.partbodyfeatureactivate('V5')
                mprog.partbodyfeatureactivate('R倒角')
                mprog.partbodyfeatureactivate('R倒角填料_1')
                mprog.partbodyfeatureactivate('R倒角填料_2')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('喉口倒角_非B')
                mprog.partbodyfeatureactivate('喉口倒圓角_非B')
                mprog.partbodyfeatureactivate('喉口倒角補料_60')
                mprog.partbodyfeatureactivate('E_倒角')
                mprog.activatefeature('110通孔', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 5)
                mprog.activatefeature('5-M5X10L(配管用)', 2)
                mprog.activatefeature('兩點組合', 0)
            elif i == 4:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('V1')
                mprog.partbodyfeatureactivate('V3')
                mprog.partbodyfeatureactivate('V5')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('喉口倒角_B')
                mprog.partbodyfeatureactivate('喉口倒角_B_圓角')
                mprog.partbodyfeatureactivate('B倒角_E段')
                mprog.partbodyfeatureactivate('喉口倒角補料_80')
                mprog.activatefeature('1-M5X10L(配管用)', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 5)
                mprog.activatefeature('5-M5X10L(配管用)', 3)
                mprog.activatefeature('兩點組合', 0)
                mprog.activatefeature('3-M5X10L(配管用)(r1)', 1)

            elif i == 5:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('V1')
                mprog.partbodyfeatureactivate('V3')
                mprog.partbodyfeatureactivate('V5')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('喉口倒角_非B')
                mprog.partbodyfeatureactivate('喉口倒圓角_非B')
                mprog.partbodyfeatureactivate('喉口倒角補料_110')
                mprog.partbodyfeatureactivate('E_倒角')
                mprog.activatefeature('1-M5X10L(配管用)', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 0)
                mprog.activatefeature('5-M5X10L(配管用)', 3)
                mprog.activatefeature('兩點組合', 0)
                mprog.activatefeature('3-M5X10L(配管用)(r1)', 2)

            elif i == 6:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('V1')
                mprog.partbodyfeatureactivate('V3')
                mprog.partbodyfeatureactivate('V5')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('喉口倒角_非B')
                mprog.partbodyfeatureactivate('喉口倒圓角_非B')
                mprog.partbodyfeatureactivate('喉口倒角補料_160')
                mprog.partbodyfeatureactivate('E_倒角')
                mprog.activatefeature('1-M5X10L(配管用)', 0)
                mprog.activatefeature('3-M5X10L(配管用)(r1)', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 0)
                mprog.activatefeature('5-M5X10L(配管用)', 5)
                mprog.activatefeature('兩點組合', 0)
            elif i == 7:
                mprog.partbodyfeatureactivate('before250_喉口')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('V1')
                mprog.partbodyfeatureactivate('V3')
                mprog.partbodyfeatureactivate('V5')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('喉口倒角_非B')
                mprog.partbodyfeatureactivate('喉口倒圓角_非B')
                mprog.partbodyfeatureactivate('喉口倒角補料_200')
                mprog.partbodyfeatureactivate('E_倒角')
                mprog.activatefeature('1-M5X10L(配管用)', 0)
                mprog.activatefeature('3-M5X10L(配管用)(r1)', 2)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 0)
                mprog.activatefeature('5-M5X10L(配管用)', 5)
                mprog.activatefeature('兩點組合', 0)
            elif i == 8:
                mprog.partbodyfeatureactivate('T250')
                mprog.partbodyfeatureactivate('Z1')
                mprog.partbodyfeatureactivate('V1_250')
                mprog.partbodyfeatureactivate('V3_250')
                mprog.partbodyfeatureactivate('V5_250')
                mprog.partbodyfeatureactivate('Z倒角')
                mprog.partbodyfeatureactivate('喉口倒角_250')
                mprog.partbodyfeatureactivate('喉口倒圓角_250')
                mprog.partbodyfeatureactivate('喉口倒角補料_250')
                mprog.partbodyfeatureactivate('E_倒角')
                mprog.activatefeature('1-M5X10L(配管用)', 0)
                mprog.activatefeature('3-M5X10L(配管用)(r1)', 0)
                mprog.activatefeature('油面劑用', 0)
                mprog.activatefeature('60通孔', 0)
                mprog.activatefeature('電動黃油泵用', 0)
                mprog.activatefeature('吊孔', 0)
                mprog.activatefeature('6-M5X16L(配管)', 0)
                mprog.activatefeature('5-M5X10L(配管用)', 0)
                mprog.activatefeature('兩點組合', 0)

        except:
            print('FRAME1 Part activate error')
        finally:
            mprog.update()
            print('FRAME1 update success')
    elif name == 'FRAME2':
        start = time.time()
        excel = epc.ExcelOp('FRAME2')
        # try:
        FRAME2_parameter_name, FRAME2_parameter_value = excel.part_parameter('FRAME2', i)

        #     print('FRAME2 Parameter change success')
        # except:
        #     print('FRAME2 Parameter change error')
        if i == 0:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('AA2')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('VV2')
            mprog.partbodyfeatureactivate('VV4')
            mprog.partbodyfeatureactivate('喉口倒角_B')
            mprog.partbodyfeatureactivate('喉口倒圓角_B')
            mprog.partbodyfeatureactivate('喉口倒角補料_45')
            mprog.partbodyfeatureactivate('R倒角')
            mprog.partbodyfeatureactivate('R倒角_qqqq')
            mprog.partbodyfeatureactivate('R倒角_G1')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段_B1倒角')
            mprog.partbodyfeatureactivate('E段_B倒角_Y')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 4)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 1)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('解角器裝置線用', 0)
            mprog.activatefeature('解角器用', 0)
            mprog.activatefeature('變頻器用', 0)
            mprog.activatefeature('解角器護蓋用', 0)
            mprog.activatefeature('M5X10L(配管用)', 0)
        elif i == 1:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('AA2')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('VV2')
            mprog.partbodyfeatureactivate('VV4')
            mprog.partbodyfeatureactivate('喉口倒角_B')
            mprog.partbodyfeatureactivate('喉口倒圓角_B')
            mprog.partbodyfeatureactivate('喉口倒角補料_60')
            mprog.partbodyfeatureactivate('R倒角')
            mprog.partbodyfeatureactivate('R倒角_qqqq')
            mprog.partbodyfeatureactivate('R倒角_G1')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段_B1倒角')
            mprog.partbodyfeatureactivate('E段_B倒角_Y')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 4)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 1)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('解角器裝置線用', 0)
            mprog.activatefeature('解角器用', 0)
            mprog.activatefeature('變頻器用', 0)
            mprog.activatefeature('解角器護蓋用', 0)
            mprog.activatefeature('M5X10L(配管用)', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
            mprog.activatefeature('1-M5X10L底孔20L配管用', 0)
        elif i == 2:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('AA2')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('VV2')
            mprog.partbodyfeatureactivate('VV4')
            mprog.partbodyfeatureactivate('喉口倒角_B')
            mprog.partbodyfeatureactivate('喉口倒圓角_B')
            mprog.partbodyfeatureactivate('喉口倒角補料_45')
            mprog.partbodyfeatureactivate('R倒角')
            mprog.partbodyfeatureactivate('R倒角_qqqq')
            mprog.partbodyfeatureactivate('R倒角_G1')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段_B1倒角')
            mprog.partbodyfeatureactivate('E段_B倒角_Y')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 4)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('解角器裝置線用', 0)
            mprog.activatefeature('解角器用', 0)
            mprog.activatefeature('變頻器用', 0)
            mprog.activatefeature('解角器護蓋用', 0)
            mprog.activatefeature('M5X10L(配管用)', 0)
            mprog.activatefeature('1-M5X10L底孔20L配管用', 0)
        elif i == 3:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('AA2')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('V1')
            mprog.partbodyfeatureactivate('V3')
            mprog.partbodyfeatureactivate('V5')
            mprog.partbodyfeatureactivate('喉口倒角_非B')
            mprog.partbodyfeatureactivate('喉口倒圓角_非B')
            mprog.partbodyfeatureactivate('喉口倒角補料_60')
            mprog.partbodyfeatureactivate('R倒角_無qqqq')
            mprog.partbodyfeatureactivate('R倒角_G1')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段倒角_非B')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 4)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('解角器裝置線用', 0)
            mprog.activatefeature('解角器用', 0)
            mprog.activatefeature('變頻器用', 0)
            mprog.activatefeature('解角器護蓋用', 0)
            mprog.activatefeature('M5X10L(配管用)', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
        elif i == 4:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('V1')
            mprog.partbodyfeatureactivate('V3')
            mprog.partbodyfeatureactivate('V5')
            mprog.partbodyfeatureactivate('喉口倒角_B')
            mprog.partbodyfeatureactivate('喉口倒圓角_B')
            mprog.partbodyfeatureactivate('喉口倒角補料_80')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段倒角_B')
            mprog.partbodyfeatureactivate('jjj4')
            mprog.partbodyfeatureactivate('mmm4')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 4)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('解角器裝置線用', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
            mprog.activatefeature('4-M8X16L', 0)
            mprog.activatefeature('2-M5(配管用)', 0)
            mprog.activatefeature('台達變頻器用10HP', 0)
            mprog.activatefeature('東元變頻器用10HP', 0)
            mprog.activatefeature('電氣箱連桿', 2)
        elif i == 5:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('V1')
            mprog.partbodyfeatureactivate('V3')
            mprog.partbodyfeatureactivate('V5')
            mprog.partbodyfeatureactivate('喉口倒角_非B')
            mprog.partbodyfeatureactivate('喉口倒圓角_非B')
            mprog.partbodyfeatureactivate('喉口倒角補料_110')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段倒角_非B')
            mprog.partbodyfeatureactivate('dd4')
            mprog.partbodyfeatureactivate('x4')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 5)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
            mprog.activatefeature('4-M8X16L', 0)
            mprog.activatefeature('2-M5(配管用)', 0)
            mprog.activatefeature('電氣箱連桿', 0)
            mprog.activatefeature('東元變頻器10,15HP440V用', 0)
            mprog.activatefeature('台達變頻器10,15HP', 0)
            mprog.activatefeature('東元變頻器,15HP220V', 0)
        elif i == 6:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('V1')
            mprog.partbodyfeatureactivate('V3')
            mprog.partbodyfeatureactivate('V5')
            mprog.partbodyfeatureactivate('喉口倒角_非B')
            mprog.partbodyfeatureactivate('喉口倒圓角_非B')
            mprog.partbodyfeatureactivate('喉口倒角補料_110')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段倒角_非B')
            mprog.partbodyfeatureactivate('ggg4')
            mprog.partbodyfeatureactivate('xx3')
            mprog.partbodyfeatureactivate('iii4')
            mprog.partbodyfeatureactivate('fff4')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 5)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
            mprog.activatefeature('4-M8X16L', 0)
            mprog.activatefeature('2-M5(配管用)', 0)
            mprog.activatefeature('電氣箱連桿', 0)
            mprog.activatefeature('東元變頻器440V,15,20HP', 0)
            mprog.activatefeature('台達變頻器440V,15,20HP；220V15HP', 0)
            mprog.activatefeature('台達變頻器220V,20HP', 0)
            mprog.activatefeature('東元變頻器220V,15,20HP', 0)
        elif i == 7:
            mprog.partbodyfeatureactivate('before250_喉口')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('V1')
            mprog.partbodyfeatureactivate('V3')
            mprog.partbodyfeatureactivate('V5')
            mprog.partbodyfeatureactivate('喉口倒角_非B')
            mprog.partbodyfeatureactivate('喉口倒圓角_非B')
            mprog.partbodyfeatureactivate('喉口倒角補料_200')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段倒角_非B')
            mprog.partbodyfeatureactivate('iii4')
            mprog.partbodyfeatureactivate('ssss4')
            mprog.partbodyfeatureactivate('sss4')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 5)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
            mprog.activatefeature('4-M8X16L', 0)
            mprog.activatefeature('2-M5(配管用)', 0)
            mprog.activatefeature('電氣箱連桿', 0)
            mprog.activatefeature('台達變頻器220V,20HP', 0)
            mprog.activatefeature('東元變頻器220V/440V,20HP', 0)
            mprog.activatefeature('台達變頻器440V,20HP', 0)
        elif i == 8:
            mprog.partbodyfeatureactivate('T250')
            mprog.partbodyfeatureactivate('Z1')
            mprog.partbodyfeatureactivate('V1_250')
            mprog.partbodyfeatureactivate('V3_250')
            mprog.partbodyfeatureactivate('V5_250')
            mprog.partbodyfeatureactivate('喉口倒角_250')
            mprog.partbodyfeatureactivate('喉口倒圓角_250')
            mprog.partbodyfeatureactivate('喉口倒角補料_250')
            mprog.partbodyfeatureactivate('Z倒角')
            mprog.partbodyfeatureactivate('E段倒角_非B')
            mprog.activatefeature('90通孔', 0)
            mprog.activatefeature('WIRE_CASING', 5)
            mprog.activatefeature('2-M5(側邊配管用)', 0)
            mprog.activatefeature('吊孔', 0)
            mprog.activatefeature('3-M5X10L(配管用)', 0)
            mprog.activatefeature('60通孔', 0)
            mprog.activatefeature('5-M5X15L(配管用)', 0)
            mprog.activatefeature('氣壓錶箱用', 0)
            mprog.activatefeature('電氣箱用', 0)
            mprog.activatefeature('2-M4X10L', 0)
            mprog.activatefeature('2-M10X20L', 0)
            mprog.activatefeature('1-M5X10L(配管用)', 0)
            mprog.activatefeature('4-M8X16L', 0)
            mprog.activatefeature('2-M5(配管用)', 0)
            mprog.activatefeature('電氣箱連桿', 0)
            mprog.activatefeature('東元變頻器25HP', 0)
            mprog.activatefeature('台達變頻器25HP', 0)


        end = time.time()
        print('FRAME2 Parameter change time: ', end - start)


    elif name == 'FRAME5':
        excel = epc.ExcelOp('FRAME5')
        try:
            FRAME5_parameter_name, FRAME5_parameter_value = excel.part_parameter('FRAME5', i)
            print('FRAME5 Parameter change success')
        except:
            print('FRAME5 Parameter change error')
        try:
            if i == 0:
                mprog.partbodyfeatureactivate('SN1-25_X')
                mprog.partbodyfeatureactivate('before80_I')
                mprog.partbodyfeatureactivate('before80_R')
                mprog.partbodyfeatureactivate('Y')
                mprog.activatefeature('2-M8通孔', 0)
                mprog.activatefeature('TY牌電磁閥用', 0)
                mprog.activatefeature('M6通孔LED', 0)
                mprog.activatefeature('PT1/2', 0)
            elif i == 1:
                mprog.partbodyfeatureactivate('before80_I')
                mprog.partbodyfeatureactivate('before80_R')
                mprog.partbodyfeatureactivate('Y')
                mprog.partbodyfeatureactivate('AA')
                mprog.activatefeature('2-M8通孔', 0)
                mprog.activatefeature('TY牌電磁閥用', 0)
                mprog.activatefeature('M6通孔LED', 0)
                mprog.activatefeature('PT1/2', 0)
            elif i == 2:
                mprog.partbodyfeatureactivate('before80_I')
                mprog.partbodyfeatureactivate('before80_R')
                mprog.partbodyfeatureactivate('Y')
                mprog.partbodyfeatureactivate('AA')
                mprog.activatefeature('2-M8通孔', 0)
                mprog.activatefeature('TY牌電磁閥用', 0)
                mprog.activatefeature('M6通孔LED', 0)
                mprog.activatefeature('PT1/2', 0)
            elif i == 3:
                mprog.partbodyfeatureactivate('before80_I')
                mprog.partbodyfeatureactivate('before80_R')
                mprog.partbodyfeatureactivate('S')
                mprog.partbodyfeatureactivate('Rx2')
                mprog.partbodyfeatureactivate('SN1-60_R')
                mprog.partbodyfeatureactivate('Chamfer.2')
                mprog.activatefeature('2-M8通孔', 0)
                mprog.activatefeature('TY牌電磁閥用', 0)
                mprog.activatefeature('M6通孔LED', 0)
            elif i == 4:
                mprog.partbodyfeatureactivate('after80_S')
                mprog.partbodyfeatureactivate('after80_R')
                mprog.partbodyfeatureactivate('Chamfer.3')
                mprog.activatefeature('2-M8通孔', 0)
                mprog.activatefeature('TY牌電磁閥用', 0)
                mprog.activatefeature('M6通孔LED', 0)
            elif i == 5:
                mprog.partbodyfeatureactivate('after80_S')
                mprog.partbodyfeatureactivate('after80_R')
                mprog.partbodyfeatureactivate('Chamfer.3')
                mprog.partbodyfeatureactivate('6-M6通C5')
                mprog.activatefeature('6-M6通', 0)
                mprog.activatefeature('M6通孔LED', 0)
            elif i == 6:
                mprog.partbodyfeatureactivate('after80_S')
                mprog.partbodyfeatureactivate('after80_R')
                mprog.partbodyfeatureactivate('Chamfer.3')
                mprog.partbodyfeatureactivate('3-M8通_C5')
                mprog.activatefeature('3-M8通', 0)
                mprog.activatefeature('M6通孔LED', 0)
            elif i == 7:
                mprog.partbodyfeatureactivate('after80_S')
                mprog.partbodyfeatureactivate('after80_R')
                mprog.partbodyfeatureactivate('Chamfer.3')
                mprog.partbodyfeatureactivate('5-M8通_C5')
                mprog.activatefeature('5-M8通', 0)
                mprog.activatefeature('M6通孔LED', 0)
            elif i == 8:
                mprog.partbodyfeatureactivate('after80_S')
                mprog.partbodyfeatureactivate('after80_R')
                mprog.partbodyfeatureactivate('Chamfer.3')
                mprog.partbodyfeatureactivate('5-M8通_C5')
                mprog.activatefeature('5-M8通', 0)
                mprog.activatefeature('M6通孔LED', 0)
        except:
            print('FRAME5 Parameter activate error')
        finally:
            try:
                mprog.Update()
                print('FRAME5 Update success')
            except:
                print('FRAME5 Update error')

change_parameter('FRAME2', 8)