# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 1045)
        self.select_item_table = QtWidgets.QTableWidget(Form)
        self.select_item_table.setGeometry(QtCore.QRect(20, 10, 621, 521))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.select_item_table.setFont(font)
        self.select_item_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.select_item_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.select_item_table.setRowCount(31)
        self.select_item_table.setColumnCount(6)
        self.select_item_table.setObjectName("select_item_table")
        self.select_item_table.horizontalHeader().setVisible(False)
        self.select_item_table.verticalHeader().setVisible(False)
        self.select_item_finish = QtWidgets.QPushButton(Form)
        self.select_item_finish.setGeometry(QtCore.QRect(20, 960, 131, 61))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.select_item_finish.setFont(font)
        self.select_item_finish.setObjectName("select_item_finish")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.select_item_finish.setText(_translate("Form", "完成設定"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
