# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(643, 472)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 611, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.AddNewRow = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.AddNewRow.setFont(font)
        self.AddNewRow.setObjectName("AddNewRow")
        self.gridLayout.addWidget(self.AddNewRow, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.T_solt = QtWidgets.QTableWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.T_solt.setFont(font)
        self.T_solt.setColumnCount(8)
        self.T_solt.setObjectName("T_solt")
        self.T_solt.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.T_solt.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.T_solt, 1, 0, 1, 2)
        self.rearrange = QtWidgets.QPushButton(Form)
        self.rearrange.setGeometry(QtCore.QRect(260, 430, 131, 28))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.rearrange.setFont(font)
        self.rearrange.setObjectName("rearrange")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.AddNewRow.setText(_translate("Form", "新增"))
        self.label.setText(_translate("Form", "橫向T溝"))
        item = self.T_solt.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.T_solt.horizontalHeaderItem(0)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(1)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(2)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(3)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(4)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(5)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(6)
        item.setText(_translate("Form", "New Column"))
        item = self.T_solt.horizontalHeaderItem(7)
        item.setText(_translate("Form", "New Column"))
        self.rearrange.setText(_translate("Form", "重新排列"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
