# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(669, 795)
        self.window_main_table = QtWidgets.QTableWidget(Form)
        self.window_main_table.setEnabled(True)
        self.window_main_table.setGeometry(QtCore.QRect(10, 10, 641, 771))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.window_main_table.setFont(font)
        self.window_main_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.window_main_table.setTabKeyNavigation(True)
        self.window_main_table.setRowCount(24)
        self.window_main_table.setColumnCount(14)
        self.window_main_table.setObjectName("window_main_table")
        self.window_main_table.horizontalHeader().setVisible(False)
        self.window_main_table.verticalHeader().setVisible(False)
        self.window_main_table.verticalHeader().setHighlightSections(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
