# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 918)
        self.window_main_table = QtWidgets.QTableWidget(Form)
        self.window_main_table.setEnabled(True)
        self.window_main_table.setGeometry(QtCore.QRect(10, 10, 641, 771))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.window_main_table.setFont(font)
        self.window_main_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.window_main_table.setTabKeyNavigation(True)
        self.window_main_table.setRowCount(24)
        self.window_main_table.setColumnCount(14)
        self.window_main_table.setObjectName("window_main_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStrikeOut(True)
        font.setKerning(True)
        item.setFont(font)
        self.window_main_table.setItem(0, 0, item)
        self.window_main_table.horizontalHeader().setVisible(False)
        self.window_main_table.verticalHeader().setVisible(False)
        self.window_main_table.verticalHeader().setHighlightSections(True)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 790, 591, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.press_preview = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.press_preview.sizePolicy().hasHeightForWidth())
        self.press_preview.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.press_preview.setFont(font)
        self.press_preview.setObjectName("press_preview")
        self.horizontalLayout.addWidget(self.press_preview)
        self.plate_preview = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plate_preview.sizePolicy().hasHeightForWidth())
        self.plate_preview.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.plate_preview.setFont(font)
        self.plate_preview.setObjectName("plate_preview")
        self.horizontalLayout.addWidget(self.plate_preview)
        self.input = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.input.setFont(font)
        self.input.setObjectName("input")
        self.horizontalLayout.addWidget(self.input)
        self.start = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.window_main_table.isSortingEnabled()
        self.window_main_table.setSortingEnabled(False)
        item = self.window_main_table.item(0, 0)
        item.setText(_translate("Form", "123"))
        self.window_main_table.setSortingEnabled(__sortingEnabled)
        self.press_preview.setText(_translate("Form", "衝頭預覽"))
        self.plate_preview.setText(_translate("Form", "平板預覽"))
        self.input.setText(_translate("Form", "匯入參數"))
        self.start.setText(_translate("Form", "完成設定\n"
"產生圖面"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
